### ISSUE TITLE
Getting unknown property: humhub\modules\usermap\Module

### ISSUE THREAD

**Issue by dentech3** [KeudellCoding/HumHub-Modules-UserMap#8]
Installed this about a week ago, seems to be working ok but have started getting this error:
```
yii\base\UnknownPropertyException: Getting unknown property: humhub\modules\usermap\Module::showOnMapCallback in /home/myhumhubdirectory/protected/vendor/yiisoft/yii2/base/Component.php:155
Stack trace:
#0 /home/myhumhubdirectory/protected/vendor/yiisoft/yii2/di/ServiceLocator.php(77): yii\base\Component->__get('showOnMapCallba...')
#1 /home/myhumhubdirectory/protected/modules/usermap/widgets/MapView.php(66): yii\di\ServiceLocator->__get('showOnMapCallba...')
#2 /home/myhumhubdirectory/protected/modules/usermap/widgets/MapView.php(47): humhub\modules\usermap\widgets\MapView->getAllUsers()
#3 /home/myhumhubdirectory/protected/humhub/components/Widget.php(63): humhub\modules\usermap\widgets\MapView->run()
#4 /home/myhumhubdirectory/protected/modules/usermap/views/map/index.php(25): humhub\components\Widget::widget(Array)
#5 /home/myhumhubdirectory/protected/vendor/yiisoft/yii2/base/View.php(348): require('/home/lacesiste...')
#6 /home/myhumhubdirectory/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/home/myhumhubdirectory...', Array)
#7 /home/myhumhubdirectory/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/home/lacesiste...', Array, Object(humhub\modules\usermap\controllers\MapController))
#8 /home/myhumhubdirectory/protected/vendor/yiisoft/yii2/base/Controller.php(410): yii\base\View->render('index', Array, Object(humhub\modules\usermap\controllers\MapController))
#9 /home/myhumhubdirectory/protected/modules/usermap/controllers/MapController.php(19): yii\base\Controller->render('index', Array)
#10 [internal function]: humhub\modules\usermap\controllers\MapController->actionIndex()
#11 /home/myhumhubdirectory/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /home/myhumhubdirectory/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#13 /home/myhumhubdirectory/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction('', Array)
#14 /home/myhumhubdirectory/protected/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction('usermap/map', Array)
#15 /home/myhumhubdirectory/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest(Object(humhub\components\Request))
#16 /home/myhumhubdirectory/index.php(25): yii\base\Application->run()
#17 {main} 
```

**Comment by KarlKeu00** [comment]
Strange, unfortunately I don't know exactly why this error occurs, but it seems to be due to an individual setting. In the next version I have now packed a try catch around the whole call, so the error should only be logged, but not lead to a crash of the page.
Please check your common.php config file.
