### ISSUE TITLE
Update Humhub 1.11

### ISSUE THREAD

**Issue by alennert** [KeudellCoding/HumHub-Modules-UserMap#9]
Module doesn't work anymore - so i tried ti install it new - the following error occures:
```
FEHLER  Thu, 21 Apr 2022 07:45:00 +0200 application
Error: Class 'humhub\modules\directory\widgets\Menu' not found in /path..to..humhub/protected/modules/usermap/config.php:19
Stack trace:
#0 /path..to..humhub/protected/humhub/components/bootstrap/ModuleAutoLoader.php(77): include()
#1 /path..to..humhub/protected/humhub/components/bootstrap/ModuleAutoLoader.php(48): humhub\components\bootstrap\ModuleAutoLoader::findModules(Array)
#2 /path..to..humhub/protected/humhub/components/bootstrap/ModuleAutoLoader.php(34): humhub\components\bootstrap\ModuleAutoLoader::locateModules()
#3 /path..to..humhub/protected/vendor/yiisoft/yii2/base/Application.php(325): humhub\components\bootstrap\ModuleAutoLoader->bootstrap(Object(humhub\components\console\Application))
#4 /path..to..humhub/protected/vendor/yiisoft/yii2/base/Application.php(271): yii\base\Application->bootstrap()
#5 /path..to..humhub/protected/vendor/yiisoft/yii2/console/Application.php(124): yii\base\Application->init()
#6 /path..to..humhub/protected/humhub/components/console/Application.php(90): yii\console\Application->init()
#7 /path..to..humhub/protected/vendor/yiisoft/yii2/base/BaseObject.php(109): humhub\components\console\Application->init()
#8 /path..to..humhub/protected/vendor/yiisoft/yii2/base/Application.php(204): yii\base\BaseObject->__construct(Array)
#9 /path..to..humhub/protected/vendor/yiisoft/yii2/console/Application.php(89): yii\base\Application->__construct(Array)
#10 /path..to..humhub/protected/humhub/components/console/Application.php(52): yii\console\Application->__construct(Array)
#11 /path..to..humhub/protected/yii(28): humhub\components\console\Application->__construct(Array)
#12 {main}
```

**Comment by lisandi** [comment]
humhub\modules\directory\

I guess the problem is solely here as the directory module had been deleted and is no more available in 1.11 afaik.

Could you please fix that problem and add a description to understand how to get the module working - Thanks!

https://community.humhub.com/comment/perma?id=41520

**Comment by KarlKeu00** [comment]
I'm on it, the update should be available within the next few days.

**Comment by Deister82** [comment]
Sorry that dont work, Same error no Installation

**Comment by KarlKeu00** [comment]
That is correct. HumHub has to confirm the modules before you can install them. Please wait until you can install version 1.2.4. I think HumHub will confirm the modules within this week.

**Comment by KarlKeu00** [comment]
Fix should be out now
